"""add SAR table

Revision ID: 1740ad739cbd
Revises: 889286c09071
Create Date: 2026-05-16 01:25:38.027456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1740ad739cbd'
down_revision: Union[str, Sequence[str], None] = '889286c09071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_employee_name'), 'checkins', ['employee_name'], unique=False)
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_employee_name'), table_name='checkins')
    op.drop_table('checkins')
    # ### end Alembic commands ###
