"""add audit log table

Revision ID: 27b91db45ef5
Revises: 1740ad739cbd
Create Date: 2026-05-16 12:00:28.747853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b91db45ef5'
down_revision: Union[str, Sequence[str], None] = '1740ad739cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_access_requests_id'), table_name='subject_access_requests')
    op.drop_table('subject_access_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_access_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('requester_name', sa.VARCHAR(), nullable=False),
    sa.Column('requester_email', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('submitted_by_user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_access_requests_id'), 'subject_access_requests', ['id'], unique=False)
    # ### end Alembic commands ###
