"""create initial tables

Revision ID: 889286c09071
Revises: 
Create Date: 2026-02-25 22:40:03.101868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889286c09071'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkins_employee_name'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_table('checkins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_name', sa.VARCHAR(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('symptoms', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_index(op.f('ix_checkins_employee_name'), 'checkins', ['employee_name'], unique=False)
    # ### end Alembic commands ###
